@startuml
skinparam componentStyle uml1

agent Admin
agent User

cloud web {
}

title online-cinema

node admin_panel {
    component nginx_admin
    database postgres_admin

    [admin_app] <-down-> postgres_admin
    nginx_admin <-down-> [admin_app]
}

node async_api {
    component nginx_async
    database redis_async
    database elastic_async
    component kibana_async

    kibana_async <-down-> elastic_async
    [async_web_api] <-down-> redis_async
    [async_web_api] <-up-> nginx_async
    elastic_async <-up-> [async_web_api]
}

node auth {
    component nginx_auth
    database redis_auth
    database postgres_auth

    redis_auth <-up-> [auth_app]
    [auth_app] <-up-> postgres_auth
    nginx_auth <-> [auth_app]
}

node ETL

node ELK {
    component apm_server
    database elastic_elk
    component kibana
    elastic_elk <-down-> kibana
    apm_server <-down-> elastic_elk
}

User --> web
Admin --> web

web <----> admin_panel
web <----> auth
web <----> async_api

auth <---down-> ELK
async_api <--down-> ELK

postgres_admin <---> ETL
elastic_async <---> ETL
@enduml