version: '3.9'

services:
  code:
    build:
      context: ../
      dockerfile: stress-testing/Dockerfile
    depends_on:
      - pg
      - clickhouse-node1-st
      - clickhouse-node2-st
      - clickhouse-node3-st
      - clickhouse-node4-st
    volumes:
      - ./result:/code/result

  pg:
    image: postgres:13
    container_name: pg
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    expose:
      - "5432"

  zookeeper-st:
    image: zookeeper:3.5
    container_name: zookeeper-st
    hostname: zookeeper

  clickhouse-node1-st:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node1-st
    hostname: clickhouse-node1
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./data/node1:/etc/clickhouse-server
    depends_on:
      - zookeeper-st

  clickhouse-node2-st:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node2-st
    hostname: clickhouse-node2
    volumes:
      - ./data/node2:/etc/clickhouse-server
    depends_on:
      - zookeeper-st

  clickhouse-node3-st:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node3-st
    hostname: clickhouse-node3
    volumes:
      - ./data/node3:/etc/clickhouse-server
    depends_on:
      - zookeeper-st

  clickhouse-node4-st:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node4-st
    hostname: clickhouse-node4
    volumes:
      - ./data/node4:/etc/clickhouse-server
    depends_on:
      - zookeeper-st
